      <div class="container-fluid">
        <div class="row">
          <div class="banner-info" style="margin-top: 90px; padding-left: 190px; padding-right: 190px; padding-bottom: 100px;">
            <!-- start maps -->
            <!-- <div class="iframe-container">
              <iframe src="https://www.google.com/maps/embed/v1/search?q=hospital%20near%20my%20location&key=AIzaSyApbqMy_ftrIpADq5OxKnqPXrFydE76-jA" width="600" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div> -->
            <div id="mapid" style="height:600px;">

            
            <script type="text/javascript">
            <?php echo "var baseUrl = '". base_url() . "';"; ?>
            navigator.geolocation.getCurrentPosition(function(location) {

              var latlng = new L.LatLng(location.coords.latitude, location.coords.longitude);
              //alert(location.coords.latitude);
              //alert(location.coords.longitude);

              var mymap = L.map('mapid').setView(latlng, 16)
              L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://mapbox.com">Mapbox</a>',
                maxZoom: 26,
                id: 'mapbox.streets',
                accessToken: 'pk.eyJ1IjoiYXJjaGllY2FrcmEiLCJhIjoiY2pvNGJyajl3MTZkYzNxbXR1em1mZGprdiJ9.H8-S6YzPsmtQuGtHU4snWg'
              }).addTo(mymap);

              var personIcon = L.icon({
                iconUrl: 'assets/images/person.png',

                iconSize:     [25, 35], // size of the icon
                iconAnchor:   [16, 75], // point of the icon which will correspond to marker's location
                popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
              });

              var rsIcon = L.icon({
                //iconUrl: 'assets/images/maps-hospital.png',
                iconUrl: '<?php echo base_url('/assets/css/images/maps-hospital.png');?>',

                iconSize:     [50, 50], // size of the icon
                iconAnchor:   [25, 50], // point of the icon which will correspond to marker's location
                popupAnchor:  [0, -40] // point from which the popup should open relative to the iconAnchor
              });

              var mylocation = L.marker(latlng).addTo(mymap).bindPopup("<b>Lokasi Anda</b>");
              //var testMarker = L.marker([-7.351679, 112.770776]).addTo(mymap);

              // Define an array. This could be done in a seperate js file.
              // This tidy formatted section could even be generated by a server-side script
              // or fetched seperately as a jsonp request.
              //-7.351679, 112.770776
              
              $.ajax({
                    url : baseUrl + "C_a_faskes/list_faskes",
                    method:'POST',  // what to expect back from the PHP script, if anything
                    success : function(response){
                        var res = JSON.parse(response);
                        var markers = [];
                        res.forEach(function(element){
                          //var isi = [element.faskes_latitude,element.faskes_longitude,'<a href="#"><h5>'+element.faskes_nama+'</h5><br><img src="'+baseUrl+'assets/upload/faskes/'+element.faskes_foto+'" style="width:250px; height:250px;" class="team-img"></a>' ]
                          //markers.push(isi);
                          var markerLocation = new L.LatLng(element.faskes_latitude, element.faskes_longitude);
                          var marker = new L.Marker(markerLocation , {icon: rsIcon});
                          mymap.addLayer(marker);
                          marker.bindPopup('<a href="'+baseUrl+'C_faskes/detail_faskes/'+element.faskes_id+'"><h5>'+element.faskes_nama+'</h5><br><img src="'+baseUrl+'assets/upload/faskes/'+element.faskes_foto+'" style="width:250px; height:250px;" class="team-img"></a>');
                        });
                        
                    }
                });
            });

            </script>
            <!-- end maps -->
            </div>
          </div>
        </div>
      </div>
