      <div class="container-fluid">
        <div class="row">
          <div class="banner-info" style="margin-top: 90px;">
            <!-- start maps -->
            <!-- <div class="iframe-container">
              <iframe src="https://www.google.com/maps/embed/v1/search?q=hospital%20near%20my%20location&key=AIzaSyApbqMy_ftrIpADq5OxKnqPXrFydE76-jA" width="600" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div> -->
            <div id="mapid" style="height:600px;">

            </div>
            <script type="text/javascript">

            navigator.geolocation.getCurrentPosition(function(location) {

              var latlng = new L.LatLng(location.coords.latitude, location.coords.longitude);
              //alert(location.coords.latitude);
              //alert(location.coords.longitude);

              var mymap = L.map('mapid').setView(latlng, 14)
              L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://mapbox.com">Mapbox</a>',
                maxZoom: 18,
                id: 'mapbox.streets',
                accessToken: 'pk.eyJ1IjoiYXJjaGllY2FrcmEiLCJhIjoiY2pvNGJyajl3MTZkYzNxbXR1em1mZGprdiJ9.H8-S6YzPsmtQuGtHU4snWg'
              }).addTo(mymap);

              var personIcon = L.icon({
                iconUrl: 'assets/images/person.png',

                iconSize:     [25, 35], // size of the icon
                iconAnchor:   [16, 75], // point of the icon which will correspond to marker's location
                popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
              });

              var rsIcon = L.icon({
                //iconUrl: 'assets/images/maps-hospital.png',
                iconUrl: '<?php echo base_url('/assets/css/images/maps-hospital.png');?>',

                iconSize:     [50, 50], // size of the icon
                iconAnchor:   [25, 50], // point of the icon which will correspond to marker's location
                popupAnchor:  [0, -40] // point from which the popup should open relative to the iconAnchor
              });

              var mylocation = L.marker(latlng).addTo(mymap).bindPopup("<b>Lokasi Anda</b>").openPopup();
              //var testMarker = L.marker([-7.351679, 112.770776]).addTo(mymap);

              // Define an array. This could be done in a seperate js file.
              // This tidy formatted section could even be generated by a server-side script
              // or fetched seperately as a jsonp request.
              //-7.351679, 112.770776
              var markers = [
                [ 112.770776, -7.351679, '<h5>Rumah Sakit Umum Bunda Waru</h5><br><img src="<?php echo base_url('assets/img/logoRS.png');?>" style="width:250px; height:250px;" alt="..." class="team-img"><br>Melayani pijet dan nganu' ],
                [ 112.779349, -7.345231, '<h5>Rumah Sakit Ibu & Anak</h5><br><img src="<?php echo base_url('assets/img/logoRS.png');?>" style="width:250px; height:250px;" alt="..." class="team-img"><br>Pondok Tjandra' ],
                [ 112.790208, -7.341471, '<h5>Rumah Sakit Umum</h5><br><img src="<?php echo base_url('assets/img/logoRS.png');?>" style="width:250px; height:250px;" alt="..." class="team-img"><br>Enak Enak' ]
              ];

              //Loop through the markers array
              for (var i=0; i<markers.length; i++) {
                var lon = markers[i][0];
                var lat = markers[i][1];
                var popupText = markers[i][2];
                var markerLocation = new L.LatLng(lat, lon);
                var marker = new L.Marker(markerLocation , {icon: rsIcon});
                mymap.addLayer(marker);
                marker.bindPopup(popupText);
              }

            });

            </script>
            <!-- end maps -->

          </div>
        </div>
      </div>
